name: Pages
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch:
    inputs:
      revisions:
        description: 'Override the computed list of tags and branches with a space-separated list of tags and branches, in order from first to last. Refer to Makefile REVISIONS declaration.'
        required: false
      prefix:
        description: 'Provide a prefix for experimental branches that need to be published alongside tags. It is ignored if revisions is overridden. Refer to the PROTOTYPE_BRANCHES_PREFIX declaration.'
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.118.2"
          extended: true
      - name: Setup swap space
        # The Hugo build can require a significant amount of memory
        uses: pierotofy/set-swap-space@49819abfb41bd9b44fb781159c033dba90353a7c
        with:
          swap-size-gb: 10
      - name: Get the list of tagged revisions (for cache)
        id: get-revisions
        run: |
          echo revisions_hash=$(cd support/OSCAL; git tag | grep -E '^v\d+\.\d+\.\d+$' | sha256sum) >> $GITHUB_OUTPUT
        shell: bash
      - name: Get the list of prototype branches (for cache)
        id: get-prototype-branches
        run: |
          # Use regular variable and not GITHUB_ENV because that only works in next step, not this one
          prefix="${{ format('{0}', github.event.inputs.prefix) || 'prototype' }}"
          branches=$(cd "${OSCAL_DIR}"; git ls-remote origin "${prefix}*" | sed -n -e "s|^.*\(refs/heads/\)\(${prefix}\)|\2|p")
          # Wildcards after a stable tag prefix like v* for v1.0.0 will not work, so generate outputs for content and data paths for next step
          echo content_paths=$(printf "site/content/models/%s/\n" $branches) >> $GITHUB_OUTPUT
          echo data_paths=$(printf "site/content/data/models/odels/%s/\n" $branches) >> $GITHUB_OUTPUT
          # Prototype branch content may change so hash branch name and current commit hash for its HEAD as restore key part
          echo branches_hash=$(cd "${OSCAL_DIR}"; git ls-remote origin "${prefix}*" | sha256sum) >> $GITHUB_OUTPUT
        shell: bash
      - name: Cache generated content for existing tags
        uses: actions/cache@v3
        with:
          # explicitly do not cache develop as they are likely to change
          path: |
            site/content/models/v*/
            site/data/models/v*/
          key: ${{ hashFiles('site/archetypes/**') }}-${{ hashFiles('support/*.sh') }}-${{ steps.get-revisions.outputs.revisions_hash }}
          # A new tagged revision will invalidate the primary cache key
          # See https://github.com/actions/cache/blob/main/tips-and-workarounds.md#update-a-cache
          restore-keys: |
            ${{ hashFiles('site/archetypes/**') }}-${{ hashFiles('support/*.sh') }}
      - name: Cache generated content for existing prototype-branches
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.get-prototype-branches.outputs.content_paths }}
            ${{ steps.get-prototype-branches.outputs.data_paths }}
          key: ${{ hashFiles('site/archetypes/**') }}-${{ hashFiles('support/*.sh') }}-${{ steps.get-prototype-branches.outputs.branches_hash }}
          restore-keys: |
            ${{ hashFiles('site/archetypes/**') }}-${{ hashFiles('support/*.sh') }}            
      - name: Build
        # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        # GHA runners have 2 CPUs
        run: |
          make site -j2 \
            ${{ github.event.inputs.revisions != '' && format('REVISIONS=''{0}''', github.event.inputs.revisions) || '' }} \
            ${{ github.event.inputs.revisions == '' && github.event.inputs.prefix && format('PROTOTYPE_BRANCHES_PREFIX=''{0}''', github.event.inputs.prefix) || '' }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@068dc23d9710f1ba62e86896f84735d869951305
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # personal_token: ${{ secrets.COMMIT_TOKEN }}
          enable_jekyll: false
          publish_dir: ./site/public
          publish_branch: nist-pages
          user_name: OSCAL GitHub Actions Bot
          user_email: oscal@nist.gov
          commit_message: Deploying website [ci deploy]
